name: AWS Cloud Resume Deployment workflow

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  deployment-job:
    name: Deploy terraform AWS resources
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: install terraform
        uses: hashicorp/setup-terraform@v2.0.3

      - name: Deploy AWS infrastructre
        run: bash scripts/deployment.sh
        shell: bash