name: AWS Cloud Resume removal workflow

on:
  workflow_dispatch:

jobs:
  destroy-job:
    name: infra destroy job
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: install terraform
        uses: hashicorp/setup-terraform@v2.0.3

      - name: Destroy AWS website
        run: terraform destroy --auto-approve
        shell: bash
